name: '[STG] - Build and Deploy Netlify FE to GCP Cloud Run'

on:
  push:
    tags:
      - 'stg-v*'
    paths-ignore:
      - '**.md'
  #pull_request:
  #  branches:
  #    - 'main'
  #  paths-ignore:
  #    - '**.md'
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  REGION: us-east1
  GCR_REPO_NAME: 'netlify-ui'
  NEXT_PUBLIC_ENV: 'staging'
  NEXT_PUBLIC_ENABLE_GOVERNANCE: 'true'
  NEXT_PUBLIC_ENABLE_STAKING: 'true'
  NEXT_PUBLIC_ENABLE_CREDIT_DELEGATION: 'true'
  NEXT_PUBLIC_API_BASEURL: 'https://aave-api-v2.aave.com'
  NEXT_PUBLIC_TRANSAK_APP_URL: 'https://global.transak.com'
  NEXT_PUBLIC_TRANSAK_API_URL: 'https://api.transak.com'
  NEXT_PUBLIC_TRANSAK_API_KEY: '799087ea-c2be-44b8-a0fe-56d96b37ee3c'
  NEXT_PUBLIC_TURNSTILE_SITE_KEY: '0x4AAAAAAABe-kMUW_1JUfT7'
  NEXT_PUBLIC_FORK_BASE_CHAIN_ID: 1
  NEXT_PUBLIC_FORK_CHAIN_ID: 1
  NEXT_PUBLIC_FORK_URL_RPC: 'https://rpc.tenderly.co/fork/1234567'
  NEXT_PUBLIC_CD_API_URL: 'https://aave-cdm-backend-asvwsyulcq-ue.a.run.app/'
  NEXT_PUBLIC_CD_SUBGRAPH_URL: 'https://api.thegraph.com/subgraphs/name/atomica-dev/solvency-risk-markets-staging'
  NEXT_PUBLIC_ATOMICA_API_URL: 'https://api.atomica.org/srm-staging/'
  NEXT_PUBLIC_CD_VAULTS_SUBGRAPH_URL: 'https://api.studio.thegraph.com/query/46833/aave-credit-delegation-v3/v1.0.4'
  NEXT_PUBLIC_GOOGLE_API_SERVICE_PRIVATE_KEY: '-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQChd3kj9NTlv2Xf\nHKkWk5ueN0nXGkjjZveNTl4iXiD7Y+wBbpxy2GBRaTc9cEoAwK4bPdA3ImR5HG2q\nkgp2kJiCfUjTwk45euCDm4dO7MH4atQqEdZTqCLDv0Nv8jUbLmzWKtGPk6qjYDye\nfxE84XOlFMBqPE4aNRYlB2kAm3u41OuXT8+KRGjj97NUXwJPICeKjKkuNFvEus3t\ntiTHFMs4C4C8v5HeQTeXsf3t+M1UGiVn6HyXrHdgN+7awcLwIUOCvaU5GuOxC8pK\nsYFesbgSbsS/+vmhFWCBS/R0Qy4VhcBGwYoJC+ZcQVSyWZt7Cny60OYRlIikPn7P\nzLxJzgO/AgMBAAECggEAAbDHXxXWUCIntg/N7L4WkDACVmhgi1JN1OK//+UeEZ5o\ntKp3TzPZF6ZzMnH6sbT9aFdGgaVFtFzqAFyvaQa3ig+Mvnws0dOUW9xk13He0Aky\nTSR1qtePpvQEMpJbIFHlSCgXnJoOXHqKopra+oOzxcPeBd65b0h6AbY+UQglDKOD\nIp3vl0r5OKQr5ADdA4hDHdupWZFuzKoaqLOKeKfpNYz8BAr+pam1Jbl6J7Ix1HML\nn3q0jzMHMzLGdCMG3x3cJHrjyApwjILDTf4i6iNj4DufCL0B/653J3fHP2YJv1Wb\nkKduEJ+/7wKMDGUlVlCopWlZTORseLPVxpuh0oNpfQKBgQDOSf1NDEJA+vYb9tRR\nXS9bke9WtiFrrh/XQOdwLsh+D3xbdtfxCAgrV97j009qUYo2iNI8AVb97q2uQEMU\nzjIgBNdyiVSxzKdExb0aCA3RAu63wqcIZsSHjkDWJ4GlAWorXrrx6TeCG12ZzJ32\ny4eIYG7viOMlMUORtXsdGq5pMwKBgQDIYGKpVRGyKIiDNzSgQd1nIW0N3BSKslfP\nwo73rVv1jzXUHctD0S2dd73BrhZRi6f4YD05uIA6/cSVc5Oh1E7NDrUKG7NSDu7B\nzUsea/qj2+QQFr6Oiawg6vwtODEYo+y8C4h4o/i/ANmiiz/A/hwu9rVE2sAtHizN\nuPo4l8+zRQKBgDccBRNkRv7dDIqD8kyaPGCWJ/5eQadmqRL0P9/0X5Ntx6cXpLC7\nmJMbsmvis8CPcAEJpEBrizXjYXq/qCwSuclcAcKTdZDaP4Vb3hzqMea4hdWJpt3T\ntoUQN7n+a+AM9LQJZp/h0fZsISFJTJn13YtNV9WeGDCDbK2scetgiV+JAoGAEtMj\nUb9BO1idgp5UHl4xu7ejNDMh5uncYBNqNRCfXBGJQBVQfF2RiIKwXBrL0/tn22jH\nN74CpggjSNsj2odEo/Umwv1ZOnNWsPRlg0Unte85nN1WJ7P9bNZGvMTTr/nuirgW\nqSbWfrNIvwGQCsSUx0C8ROy8M0DreqRPNbPlenUCgYEAvcmYvyxfq0V4z36az8HP\npUT0I8wqZHuQ1koDH1D1uWIVkDhw8gBa0sLclMPXt0BXyKWYdBBAzNomK5ibPTX5\nZXTONx25eoxtsd9GxoP9GHakyCcM+g2bdxJu2nxQsTGdqiMtvvEv8C15hGkaAUfa\nBExYby0ciok1Xp7+ugFZNnI=\n-----END PRIVATE KEY-----\n'
  NEXT_PUBLIC_GOOGLE_API_SERVICE_CLIENT_ID: 'aave-cd@aave-cd.iam.gserviceaccount.com'

jobs:
  Build_Push_Deploy:
    name: Setup, Build, Push and Deploy
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Authenticate with Google Cloud
      - name: Configure GCP credentials
        id: 'auth'
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      # Setup gcloud CLI/SDK
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Authorize Docker push
        run: gcloud auth configure-docker

      - name: Build and tag the docker image
        run: |-
          docker build . --tag gcr.io/$PROJECT_ID/$GCR_REPO_NAME:$GITHUB_REF_NAME \
          --build-arg next_public_env=$NEXT_PUBLIC_ENV \
          --build-arg next_public_enable_governance=$NEXT_PUBLIC_ENABLE_GOVERNANCE \
          --build-arg next_public_enable_staking=$NEXT_PUBLIC_ENABLE_STAKING \
          --build-arg next_public_enable_credit_delegation=$NEXT_PUBLIC_ENABLE_CREDIT_DELEGATION \
          --build-arg next_public_api_baseurl=$NEXT_PUBLIC_API_BASEURL \
          --build-arg next_public_transak_app_url=$NEXT_PUBLIC_TRANSAK_APP_URL \
          --build-arg next_public_transak_api_url=$NEXT_PUBLIC_TRANSAK_API_URL \
          --build-arg next_public_transak_api_key=$NEXT_PUBLIC_TRANSAK_API_KEY \
          --build-arg next_public_turnstile_site_key=$NEXT_PUBLIC_TURNSTILE_SITE_KEY \
          --build-arg next_public_fork_base_chain_id=$NEXT_PUBLIC_FORK_BASE_CHAIN_ID \
          --build-arg next_public_fork_chain_id=$NEXT_PUBLIC_FORK_CHAIN_ID \
          --build-arg next_public_fork_url_rpc=$NEXT_PUBLIC_FORK_URL_RPC \
          --build-arg next_public_cd_api_url=$NEXT_PUBLIC_CD_API_URL \
          --build-arg next_public_cd_subgraph_url=$NEXT_PUBLIC_CD_SUBGRAPH_URL \
          --build-arg next_public_atomica_api_url=$NEXT_PUBLIC_ATOMICA_API_URL \
          --build-arg next_public_cd_vaults_subgraph_url=$NEXT_PUBLIC_CD_VAULTS_SUBGRAPH_URL \
          --build-arg next_public_google_api_service_private_key=$NEXT_PUBLIC_GOOGLE_API_SERVICE_PRIVATE_KEY \
          --build-arg next_public_google_api_service_client_id=$NEXT_PUBLIC_GOOGLE_API_SERVICE_CLIENT_ID

      - name: Push the image to the Google Container Registry (GCR)
        run: |-
          docker push gcr.io/$PROJECT_ID/$GCR_REPO_NAME:$GITHUB_REF_NAME

      - name: Deploy
        run: |-
          gcloud run deploy $GCR_REPO_NAME \
          --region $REGION \
          --image gcr.io/$PROJECT_ID/$GCR_REPO_NAME:$GITHUB_REF_NAME \
          --platform "managed" \
          --allow-unauthenticated \
          --min-instances 1 \
          --quiet
